### ISSUE TITLE
Option.Parser customize our keys

### ISSUE THREAD

**Issue by erikasoncin** [wintoncode/Winton.Extensions.Configuration.Consul#101]
Hi,

We are using an application .NET CORE 2.2 that should also be implemented in 3.2.
Now the Parsers expects to manipulate KV, we would expect that also in this class _KVPairExtensions.cs_ line of code 19
`using Stream stream = new MemoryStream(kvPair.Value);` 
in the stream both key and value would be injected because in our case we need to remove the underscores in our keys, then both can be used to populate the IConfiguration.

Here's what we need in MyCustomConfigurationParser.cs:

`public IDictionary<string, string> Parse(Stream stream)`
        `{`

            var parsedDictionary = _configurationParser.Parse(stream);
            return parsedDictionary.ToDictionary(kv => kv.Key.Replace("_", string.Empty), kv => kv.Value);   
     }
but in kv.Key is empty. Our configuration is as a tree.
I hope I’ve made myself clear.

Thank you.

**Comment by davidalpert** [comment]
@Choc13 We have a similar use case, in that we would like the ability to rewrite some of the values, based on the full key, so we would also need the `key` part injected, but the fully qualified consul key.

I think both our concerns could be handled by updating the signature of `IConfigurationParser.Parse(...)` to take in a key argument?

```csharp
    /// <summary>
    ///     Defines how the configuration loaded from Consul should be parsed.
    /// </summary>
    public interface IConfigurationParser
    {
        /// <summary>
        ///     Parse the <see cref="Stream" /> into a dictionary.
        /// </summary>
        /// <param name="baseKey">The base configuration key at which this <paramref name="valueStream"/> was read.</param>
        /// <param name="valueStream">A stream representing the value to parse.</param>
        /// <returns>A dictionary representing the configuration in a flattened form.</returns>
        IDictionary<string, string> Parse(string baseKey, Stream valueStream);
    }
```

I have a branch locally where I have this working and all tests are passing, although this would be a breaking change to the `IConfigurationParser` interface and cause any custom clients to fix their `Parse(...)` method to match.

Another non-breaking approach might be to add a new marker interface which config parsers could implement to opt-in to the opportunity to rewrite a configuration key pair before it gets returned.

For example:
```csharp
    /// <summary>
    ///     Allows clients to rewrite configuration keys as they are parsed.
    /// </summary>
    public interface IConfigurationKeyValueRewriter
    {
        /// <summary>
        ///     Rewrites a configuration KeyValuePair.
        /// </summary>
        /// <param name="pair">The source <see cref="KeyValuePair{TKey, TValue}"/> pair read from Consul.</param>
        /// <returns>The rewritten <see cref="KeyValuePair{TKey, TValue}"/>.</returns>
        KeyValuePair<string, string> Rewrite(KeyValuePair<string, string> pair);
    }
```

I have another branch locally where I spike this second method out as well, and all tests are passing.

Perhaps the non-breaking opt-in pattern makes more sense now, and could be refactored to the first pattern (passing the key into the parser's `Parse(...)` method) in some future release where there are other breaking changes?

**Comment by Choc13** [comment]
@davidalpert thanks for the investigation into this one. Do you think we could have our cake and eat it by using C#8's default interface implementation feature? This code in here is using C#8 already, but not sure whether this would mean clients also need to be using C#8 or above to utilise the default implementation in their code? What do you think?

@erikasoncin do changes proposed by @davidalpert support your use case? I'm not sure I fully understood your situation.

**Comment by Choc13** [comment]
Having thought about this some more, it seems like there might be an alternative approach here, but I'd need to understand both of your requirements a little bit more first.

Could you tell me whether you want to use the full consul key to modify the values that are parsed, or do you, more simply, just want to have control over how the consul keys are turned into configuration keys?

If it's the latter, then we can address this by adding a `Func` (or interface implementation if you want DI available) called `KeyParser` to `ConsulConfigurationSource` that we can invoke by passing in the raw consul key and letting that take care of turning it into a configuration key (with maybe a bit of sanity checking afterwards). This would actually just be a more generalised version of the `KeyToRemove` property that we already let people set to control which portion is stripped off of the consul keys. We can then default `KeyParser` to do what the code currently does and add a note to `KeyToRemove` to let clients know that is has no effect is `KeyParser` is also set.

Let me know if that would work for you use cases?

**Comment by davidalpert** [comment]
in my use case we have a need to preview each consul key/value as a pair, as we store some specific token values in our Consul values and want to replace those tokens with lookups into external systems (using the full consul key as a lookup key) before handing them to the application.

**Comment by Choc13** [comment]
@davidalpert that's interesting, thanks for the details on your use case. I see now that you really need the interface that gives you access to the whole consul KVPair. Would it be fair to say that you basically want to be able to write your own definition of [`KVPairExtensions.ConvertToConfig`](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/master/src/Winton.Extensions.Configuration.Consul/Extensions/KVPairExtensions.cs#L14)? 

If so, I think your solution in the PR is the way to go, but I think maybe we should introduce it as a property called `KVParser` on `ConsulConfigurationSource` which is of type `Func<KVPair, IEnumerable<KeyValuePair<string, string>>`. I think I am also tempted to then deprecate the `Parser` property and specify a `ValueParser` property instead of type `Func<Stream, IEnumerable<KeyValuePair<string, string>>>`. With the distinction being that most people set neither and get the default Json parsing behaviour. People who want to change the way values are parsed can utilise `ValueParser` and `KeyToRemove` and those who want full control over the parsing can use `KVParser`? What do you think to this suggestion? I think if I was designing it from scratch I'd go down this route, rather than using interfaces. Please let me know though if having the interfaces is useful for other reasons (DI springs to mind) over the `Func` types?

**Comment by davidalpert** [comment]
Thank you for the discussion.  I believe that you have captured my use case correctly, and that this would handle @erikasoncin's use case also.

So long as I can intercept and optionally rewrite the fully qualified key and value before they get set on the `Data` dictionary for exposure to the app I'm happy.

I have no strong feelings for interfaces vs `Func` in this case; while DI might be useful we are configuring this configuration source explicitly at startup, so setting a few `Func`s would be fine.

**Comment by Choc13** [comment]
Great!

I think what keeps going around in my mind is that to offer the most flexibility we want to give people the ability to write a `Func<KVPair, IEnumerable<KeyValuePair<string, string>>>` so that they get access to the unmodified `KVPair` from Consul, but for most people it's sufficient to just give them control over how the values are parsed. So in the first case you have the raw consul key, but in the second case something needs to have taken care of turning that into a config key for you already.

So I think it's a little more complicated than just defaulting the implementation of parsing from a key and a value as `IDictionary<string, string> Parse(string baseKey, Stream valueStream) => Parse(valueStream);` because I think you need to default the key parsing behaviour to what we already have. Obviously that's not impossible to do, but I guess what I'm saying is that these two use cases are mutually exclusive, so having them on the same interface is perhaps a bit confusing for implementers anyway and only providing one method on the interface would mean implementers always have to deal with key parsing logic when they don't want to think about it.

How do you want to proceed from here? Do you want to have a go at the `Func` based approach or would you like me to? I realise you've written quite a bit of code already investigating these different approaches.

**Comment by davidalpert** [comment]
I don't see handling keys and values as two separate concerns, myself. 

My idea with the `IDictionary<string, string> Parse(string baseKey, Stream valueStream) => Parse(valueStream);` implementation was that this would default to the existing behaviour of parsing a value independent of the key unless you wanted to intercept it and "parse" the key also.  In other words you could choose to interpret the `Parse(...)` call as parsing just the value or parsing the key/value as a pair.

I'm not sure where the `Func<KVPair, IEnumberable<KeyValuePair<string,string>>>` signature would fit in the processing, so if you have a clear idea on that I would defer to you to implement or provide more detail.

I could see a `Func<KeyValuePair<string,string>,KeyValuePair<string,string>> RewriteConfigPair {get;set;}` property on the `IConsulConfigurationSource interface maybe?  Does that sound like what you had in mind?

At the end of the day I defer to the owners of this project and am happy to help in whatever way I can.

**Comment by davidalpert** [comment]
Ah, perhaps I see what you were getting at.

`Func<KVPair, IEnumerable<KeyValuePair<string,string>>` is effectively the signature of the static helper method `KVPairExtensions.ConvertToConfig` so if we were to:

1. Add a new property to `ConsulConfigurationSource` like this:
```csharp
    Func<KVPair, IEnumerable<KeyValuePair<string,string>> ConvertToConfig { get; set; } 
```
2. Set the default implementation (more or less) to `KVPairExtensions.ConvertToConfig`

That is another way to introduce a seam in a non-breaking way which would allow us to set our own custom `Func<KVPair, IEnumerable<KeyValuePair<string,string>>` to be used instead, and if we do this correctly when no one customizes that property they get the current behavior.

I can take a crack at that for sure.

**Comment by Choc13** [comment]
@davidalpert thats exactly it. Sorry, I think my message wasn’t very well articulated before, but you’ve got it now. I’ve been a bit busy recently so didn’t have time to write the code, which would have made the explanation clearer.

I think having the ability to parse the raw KVConfig is important because it’s give clients the most flexibility, because we haven’t yet tampered with the keys at all.

Thanks for taking a crack at this. Your efforts are very much appreciated.

**Comment by davidalpert** [comment]
Here is another PR (https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/103)  which exposes that `ConvertToConfig` property on `IConsulConfigurationSource`.

I am happy to contribute to this project; we have found it very useful and it is a pleasure to give back.

**Comment by Choc13** [comment]
[3.1.0](https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul/3.1.0) has been published to NuGet which contains these changes. Thanks to @davidalpert for doing this work.
