### ISSUE TITLE
Bug: Getting keys from wrong service with similar name

### ISSUE THREAD

**Issue by DR9885** [wintoncode/Winton.Extensions.Configuration.Consul#117]
Getting keys from wrong service with similar name... but wasn't expecting this.

### Example Consul Keys
```
v1/Company.Service.Name/Foo/Foo = bar1
v1/Company.Service.Name.Subname/Foo/Foo = bar2
```

### Example Service Setup
```
        hostBuilder
                .ConfigureAppConfiguration((context, builder) =>
                {
                    builder.AddConsul("v1/Company.Service.Name", x =>
                    {
                        x.Parser = new SimpleConfigurationParser();
                        x.Optional = true;
                        x.ReloadOnChange = true;
                    });
                })
```

### Expected .NET IConfiguration Result
```
"Foo:Foo" = bar1
```

### Actual .NET IConfiguration Result
```
".Subname:Foo:Foo" = bar2
"Foo:Foo" = bar1
```

**Comment by Choc13** [comment]
Hi @DR9885 thanks for reporting this. Could you confirm for me that this is just pointing to a single Consul hostname? As in, you have set:

```csharp
.AddConsul(
    "v1/Company.Service.Name",
    options =>
    {
         options.ConsulConfigurationOptions = cco => { cco.Address = new Uri("http://your-consul-host"); };
    })
```

If that's the case then I'm wondering if this is something to do with how the Consul API resolves keys that are a partial match. It should be possible to test that quite quickly by running Consul, setting up the keys like you have and then seeing what the API returns. I'll give it a go now. We might need a smarter way to handle multiple matches.

**Comment by Choc13** [comment]
So yeah the Consul API will return all keys that match the prefix, which makes sense because we want to get all keys under the root key specified. However, in your case that's obviously causing an issue because it's also pulling in the config from the service whose name has the same prefix. One "quick fix" for this is to add the trailing `/` to your root key when configuring Consul. I've tested this with the Consul HTTP endpoints directly and that will then cause it to only match on the `Company.Service.Name` keys. I'm not 100% sure this behaviour will carry across to the Consul .NET client, but it would be worth a try. So you'd just need to set it up like this:

```csharp
.AddConsul(
    "v1/Company.Service.Name/", // <-- note the trailing forward slash here
    options =>
    {
         // other options
    })
```

A better fix would be for this library to only use keys whose root key is an exact match. We could then also offer a configuration option to allow partial matches for anyone that was actually making use of that behaviour (although that behaviour was unintended).

**Comment by DR9885** [comment]
Fix works, thanks!

**Comment by Choc13** [comment]
Cool, glad it's worked. 

Just going to add this here in case anyone wants to open a PR and make this improvement internally. If we wanted to make this behaviour more explicit then I think the way to do it would be to do something like this in `ConsulConfigurationProvider.GetKvPairs()`

```csharp
var key = _source.AllowKeyPrefixMatch ? _source.Key : $"{_source.Key.TrimEnd('/')}/";

var result =
    await consulClient
        .KV
        .List(key, queryOptions, cancellationToken)
        .ConfigureAwait(false);
```

Which would mean that when configuring this config provider someone could write:

```csharp
.AddConsul(
    "v1/Company.Service.Name",
    options =>
    {
        options.ConsulConfigurationOptions = cco => { cco.Address = new Uri("http://your-consul-host"); };
        options.AllowKeyPrefixMatch = false; // <-- Note this line would ensure exact matches when querying consul keys
    })
```

That way the library would take care of always adding the trailing slash when query Consul. We'd probably have to default `AllowKeyPrefixMatch` to `true` for the time being though given that it would technically be a breaking change otherwise.

Mostly though I think this behaviour just needs documenting somewhere in the README so that regardless of whether we implement `AllowKeyPrefixMatch` it's clear to people that by default Consul will match greedily unless the key is terminated with a `/`.
