### ISSUE TITLE
Trigger CancellationTokenSource For ConsulConfigurationProvider

### ISSUE THREAD

**Issue by muratyuceer** [wintoncode/Winton.Extensions.Configuration.Consul#133]
Hi,

How can I manually trigger ConsulConfigurationProvider => Dispose or CancellationToken from my project?

Our project sometimes throw error like below, I suspect that this error is logged when the application pool in IIS is recycled, due to using this provider on legacy .NET Framework (4.8).

```
Unable to watchChanges in Consul (consecutive failure count: 1) Shared folder due to A task was canceled. and stacktrace    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Consul.GetRequest`1.<Execute>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Winton.Extensions.Configuration.Consul.ConsulConfigurationProvider.<GetKvPairs>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Winton.Extensions.Configuration.Consul.ConsulConfigurationProvider.<PollingLoop>d__11.MoveNext()
```

Additionally, since this error appears in the logs multiple times, I suspect it's as if the PollingLoop Task is running unnecessarily in parallel. Could it be that the PollingLoop is somehow started concurrently during startup?

![image](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/assets/25631692/d6bb210d-77b1-4231-bf82-33427d16c580)

**Comment by Choc13** [comment]
Hi @muratyuceer 

Thanks for raising this. Having looked through the code again I don't think there is a way to access the `CancellationTokenSource` as it is created [inside the `ConsulConfigurationProvider` class](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/master/src/Winton.Extensions.Configuration.Consul/ConsulConfigurationProvider.cs#L43).

I think this design was semi-deliberate at the time because I felt like it wasn't correct to let clients stop the polling loop and instead have the `ConsulConfigurationProvider` manage that via it's own `Dispose` method. However, I don't think there's any reason we can't add a `WatchCancellationTokenSource` in the `IConsulConfigurationSource` interface so that clients could pass their own instance in which they control if they want to be able to stop the polling loop from outside. 

This still wouldn't address your problem though because the way that `CancellationToken`s work I believe is to raise a [`TaskCanceledException`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception?view=net-7.0). This causes [`catch` block in the `PollingLoop`](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/master/src/Winton.Extensions.Configuration.Consul/ConsulConfigurationProvider.cs#L146) to be called when the `ConsulConfigurationProvider` gets disposed. However, we should make a change in that catch block to ignore `TaskCanceledException`s if the `_cancelationTokenSource` is in the `Canceled` state. I've never loved how the .NET api chooses to handle cancelation like this, but it is what it is, so we should fix the code here to handle that situation properly. 

If you want to have a go a PR feel free, otherwise I can try and find sometime (probably next week to make the second change). I'm not totally sure the first change is necessary, but if you have a use for that then let me know.

As for the fact you're getting multiple errors reported there should only be one `PollingLoop` initiated per instance of `ConsulConfigurationProvider`. Are you perhaps creating multiple instances to monitor several keys or several different Consul instances?

**Comment by Choc13** [comment]
We could also add the ability too for the [`OnWatchException`](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/master/src/Winton.Extensions.Configuration.Consul/IConsulConfigurationSource.cs#L82C51-L82C51) so that people can signal to stop the polling loop at that point, rather than just injecting a delay. Although this would likely require a breaking change to the API unless we designated `TimeSpan.Zero` as a special value which means stop polling, but I don't like that design.

**Comment by muratyuceer** [comment]
Hi @Choc13 

Thank you for your support. The 'task canceled' error has led me to discover a larger issue. I'm still investigating, but somehow, even after deploying new code to the production server, the previous code's PollingLoop task continues to run. That's why we encounter this error multiple times when a task is canceled. Right now, my priority is to trigger the CancellationTokenSource externally, and I will create a pull request regarding this and provide updates.

**Comment by muratyuceer** [comment]
Hi @Choc13 

I created pr for cancelation token source

**Comment by Choc13** [comment]
Thanks for raising the PR, just a minor comment on the doc string, but otherwise looking good. 

As to your other point about catching errors and graceful shutdown, I'm pretty sure we need to modify the `PollingLoop` inside `ConsulConfigurationProvider` to handle the `TaskCanceledException`. I think it should just be as simple as adding a `when` clause to the `catch` like this:

```csharp
catch (Exception exception) when (!cancellationToken.IsCancellationRequested)
{
     // ...
}
```

**Comment by Choc13** [comment]
3.4.0 has been released which contains these changes.
