### ISSUE TITLE
Don't poll back to back

### ISSUE THREAD

**Issue by florinbadea** [wintoncode/Winton.Extensions.Configuration.Consul#140]
Would it be a good idea to not poll back-to-back? Maybe connections to consul are expensive (take a long time) and there should be an option to check for Consul changes every X seconds

**Comment by Choc13** [comment]
Hi @florinbadea 

The polling mechanism used by the Consul lib is long polling. This means that it opens a connection to ask for a new version of the key. This connection remains open for some time (I don't remember exactly but it's something like 5 minutes). Only after that time has elapsed will it return a response if there is no update. So it is then fine to poll again immediately. 

If the keys are not changing then it will only make a call every X seconds. If the key is updating then it will return as soon as it sees that update and then start a new connection for the next change. So only if the value for a key was constantly changing would you see lots of requests close together. 

The docs in the README describe the `PollWaitTime` parameter which you can use to customise this timeout. 

Let me know if you're observing different behaviour to this though.

**Comment by florinbadea** [comment]
so basically if the key does not change, the client waits for PollWaitTime before doing another poll. i guess i wanted a way to prevent the connection from being made in the first place, not sure exactly why. 

i did manage to find a 'solution' for this, even though i think it might be a hack.

The way i 'solved it' (i think) was by setting ReloadOnChange=False and adding a separate hosted service that calls Reload() on IConfigurationRoot every X minutes. That way all underlying IConfigurationProviders are forced to reload.

**Comment by Choc13** [comment]
> so basically if the key does not change, the client waits for PollWaitTime before doing another poll. 

Pretty much. Although it's a (little) bit smarter than this. I would suggest reading about HTTP long polling (it's not specific to Consul). TLDR; the client (our config provider) makes a request with the last know version number it saw for that key. If the version number has not changed Consul will hold that connection open and after 5 minutes will send a response to indicate nothing has changed. This is cheap for us unless you're somehow maxing out open HTTP connections, but this should only have one connection per root key that you've configured in your app.

Where long polling is smarter is that if the value changes whilst you have that connection open Consul will return immediately with the new value and the new version number. So changes are propagated in "near real-time". 

> i guess i wanted a way to prevent the connection from being made in the first place, not sure exactly why.

You can't get the config if you don't make a connection 😜 
What problem are you trying to solve exactly? It sounds like you might be trying to optimise away a problem that doesn't exist. Are you seeing performance issues?

> i did manage to find a 'solution' for this, even though i think it might be a hack.
> 
> The way i 'solved it' (i think) was by setting ReloadOnChange=False and adding a separate hosted service that calls Reload() on IConfigurationRoot every X minutes. That way all underlying IConfigurationProviders are forced to reload.

This sounds a bit sub-optimal, although it depends on what you're optimising for. In this scenario you're falling back to regular polling. This means changes will not be propagated back to you until the next poll call. In the long polling approach you will see changes almost immediately. You're also going to use the same number of connections here as you would with long polling. The only difference is they won't be held open the whole time. So the only reason I would opt for this would be if I was starving open HTTP connections from my app. I'm not sure what the max number is, but I'd be surprised if you were hitting that limit just from this config provider. 

In general you want to rely on each config providers in-built watch/reload functionality as it will be able to make use of mechanisms specific to that provider. It's also likely to have been optimised and tested. 

Manually calling `Reload()` can be useful in scenarios where you want to update the config based on some external stimulus (maybe because you have an app where only certain users can update config and you capture an event each time they done this - that way you could disable watching and only reload on those triggers). 

If you let me know the particular problem you're trying to solve I can probably offer some more specific advice.

**Comment by florinbadea** [comment]
i think it's like you say. i'm trying to optimize a problem that does not exist. 
what i wanted to do is to avoid any connections to consul for 10-15 minutes at a time, for example. i don't mind if the consul changes are not seen by apps for this period of time. each app will have only 2 root keys: 1 for service configurations and 1 for FeatureFlags (apply to all services). i don't have a lot of apps in the first place (under 10 apps).

**Comment by Choc13** [comment]
OK in this case I would just set `PollWaitTimeout` to be 10 minutes (the maximum) then instead of the default 5. This will get you the behaviour you want. Although the default 5 minutes is probably also low frequency enough. 

You can read more about this mechanism and the wait time, as it relates to Consul, in their [docs](https://developer.hashicorp.com/consul/api-docs/features/blocking)
