### ISSUE TITLE
Consul Reload Polling Interval

### ISSUE THREAD

**Issue by SudharsanN** [wintoncode/Winton.Extensions.Configuration.Consul#16]
When we set the ReloadOnChange property of ConsulConfigurationSource to true, what is the time interval after which the package poll Consul for changes? Is there way to specify the time interval for polling? I couldn't locate a property in ConsulConfigruationSource to set the interval.  Basically, we don't want to keep polling Consul for changes. Rather, we would like to poll it for every set interval of time like 10 mins or so. Is there a way to do this?

**Comment by Choc13** [comment]
Hi @SudharsanN,

We are making use of [Consul's support](https://www.consul.io/api/index.html#blocking-queries) for [long polling](https://www.pubnub.com/blog/2014-12-01-http-long-polling/). Rather than the client polling Consul periodically to check for updates there is instead a long-lived HTTP connection open with Consul. If the value of the key value pair is updated then Consul will respond with the new value immediately. A new long-lived connection is then opened to await further changes. So it is by design that there is no option to configure the polling interval, as there is no polling interval to configure. Changes should propagate through in near real-time.

Obviously HTTP requests eventually timeout. So once that happens the client will open another long-lived connection to Consul. It will keep doing this every time there is either an update or the connection times out. If you want to change the lifetime of the long-polling connection, for instance if you are worried about the number of requests that are being made, then you can set this value in code. We are using [Consul.Net](https://github.com/PlayFab/consuldotnet) to communicate with Consul, which provides a [`WaitTime`](https://github.com/PlayFab/consuldotnet/blob/2f3b4f1899e8cc5a3c73eaa2c44aff445ffe103f/Consul/Client.cs#L174) option in its [`ConsulClientConfiguration `](https://github.com/PlayFab/consuldotnet/blob/2f3b4f1899e8cc5a3c73eaa2c44aff445ffe103f/Consul/Client.cs#L68) class. Therefore to set this you would do the following:

```
var builder = new ConfigurationBuilder()
    .AddConsul(
        $"{env.ApplicationName}.{env.EnvironmentName}",
        cancellationTokenSource.Token,
        options => {
            options.ReloadOnChange = true;
            options.ConsulConfigurationOptions = (cco) => {
                cco.WaitTime = TimeSpan.FromMinutes(1);
            };
        });
```

Does that help you? If not, could you elaborate on why you don't wan't to keep polling Consul and the constraints you are facing in your application?

**Comment by SudharsanN** [comment]
This clarifies my question. Will use the WaitTime property as you
suggested. Thank you, Matt.
