### ISSUE TITLE
Configuration Reload Event??

### ISSUE THREAD

**Issue by SudharsanN** [wintoncode/Winton.Extensions.Configuration.Consul#17]
When Winton reloads the configuration from Consul, is there any event that we can listen to? I am asking so since we would like to invalidate our local cache once configuration gets reloaded. Currently, we are not sure of how to achieve this. Any suggestion to achieve the above?

**Comment by Choc13** [comment]
Hi @SudharsanN,

This library is nothing more than an additional configuration source for the .NET Core Configuration system. This means that you can use the following code to listen for configuration changes as you would for any configuration in .NET Core. 

```
ChangeToken.OnChange(
    Configuration.GetReloadToken,
    () =>
    {
        // Your code here to run when there is a change
    }
);
```

Note, you'll need to include the `Microsoft.Extensions.Primitives` namespace to make sure `ChangeToken` is available. 

Also, make sure you have enabled `ReloadOnChange` in the options when adding Consul as configuration source otherwise it wont be listening for changes. For instance: 

```
var builder = new ConfigurationBuilder()
   .AddConsul(
        $"appsettings.json", 
        _consulConfigCancellationTokenSource.Token,
        options => {
            options.ReloadOnChange = true;
        });
```

If you would like more information on how configuration reloading is done in .NET Core then you can see the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration) or there is some good information in this [blog post](https://blog.rraghur.in/2017/02/08/reloading-configuration-in-.net-core/).

Let me know if this solves your problem.

Thanks, 

Matt

**Comment by SudharsanN** [comment]
Thanks for the clarification Matt.
