### ISSUE TITLE
Support 'OnConfigChanged' in order to action something upon a config change

### ISSUE THREAD

**Issue by basovic88** [wintoncode/Winton.Extensions.Configuration.Consul#37]
Hi guys,

I have forked this project to add an enhancement. I've added an `OnConfigChanged` Action in the `ConsulConfigurationSource`. This action is called whenever the `ChangeToken` fires it's `OnChange` method.

What's the use case? Well, in my case I need to restart some computation services to work with the updated configuration values. I can now do this by hooking up some logic to `OnConfigChanged`. Like this:

```csharp
configBuilder
     .AddConsul(
         "MyService.Development"
         cancellationTokenSource.Token,
         options =>
         {
             // ....
             options.ReloadOnChange = true;
             // Ta da.... Here it is
             options.OnConfigChanged = _ => { Console.WriteLine("Oh my god, change is upon us! We need to do stuff.") }
         })
     .AddEnvironmentVariables()
     .Build();
```

Is this worth a pull request? Or, better even, are there perhaps existing ways to achieve this? Let me know.
NB: The full commit is visible [here](https://github.com/basovic88/Winton.Extensions.Configuration.Consul/commit/29c1d97643b0a0ee2133d584e267383c66744821).

**Comment by Choc13** [comment]
Hi @basovic88,

If I've understood your requirements correctly then you should be able to do this at the `[IConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=aspnetcore-2.0)` abstraction layer rather than at the config provider layer. This was designed into the configuration system by Microsoft. This library is just another configuration provider, but the idea is that applications interact with `[IConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=aspnetcore-2.0)` rather than with the underlying providers so that they are able to consume configuration from multiple sources in a uniform manner and without knowing (or caring) where the config values come from.

More specifically, the `[IConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=aspnetcore-2.0)` object that is returned when you call `configBuilder.Build()` has a `[GetReloadToken()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.getreloadtoken?view=aspnetcore-2.0#Microsoft_Extensions_Configuration_IConfiguration_GetReloadToken)` method on it which returns an `[IChangeToken](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.ichangetoken?view=aspnetcore-2.0)`. There is actually an example of this in the [blog post](https://tech.winton.com/2016/12/configuring-net-core-applications-using-consul/) that we wrote introducing this library. The pertinent part is the following code snippet:

```
ChangeToken.OnChange(
    Configuration.GetReloadToken,
    () => logger.LogInformation("Config Reloaded!")
); 
```

So providing that you set `options.ReloadOnChange = true;` (as you have done in your sample above) when adding Consul as a configuration source then the resulting `IConfiguration` will be notified of changes by the Consul provider when they occur.

I hope that helps.

**Comment by basovic88** [comment]
Hi Matt,

Thanks for you response and for the blog post. That certainly helps! The example is perfect.

Perhaps you could add it (or the link to the blog post) to the README.md?

Kind regards,
Bas
