### ISSUE TITLE
will this package cache kv in client side in case consul server is unavailable for a while?

### ISSUE THREAD

**Issue by hiwjcn** [wintoncode/Winton.Extensions.Configuration.Consul#73]
will this package cache kv in client side in case consul server is unavailable for a while?

**Comment by Choc13** [comment]
Hi @hiwjcn,

This package is a bridge between Consul's KV store and ASP.NET Core's configuration system. So once the configuration has been loaded, at application startup, then it will be in memory for the rest of the program in the ASP.NET Core configuration system. So yes, in effect it is cached, but not by this library directly. If the initial load fails then you can customise the behaviour of how that is handled by setting the `OnLoadException` action in the options.

In the case of a configuration reload because of a change in Consul, then by default it will not replace the existing config if the reload errors or returns nothing. You can also control the error handling behaviour during a reload by setting the `OnWatchException` action in the options.

I hope that answers your question.

**Comment by hiwjcn** [comment]
thanks, that solves my problem
