### ISSUE TITLE
Question: Why are ConsulConfigurationClient internal

### ISSUE THREAD

**Issue by HaroonSaid** [wintoncode/Winton.Extensions.Configuration.Consul#77]
I am trying to implement a version for K/V retrieval for NET Framework 4.7.1 using ```KeyValueConfigBuilder``` (Microsoft.Configuration.ConfigurationBuilders) in order to migrate legacy .NET Frameworks to Consul.

Why is ConsulConfigurationClient an internal class?

**Comment by Choc13** [comment]
Hi @HaroonSaid,

`ConsulConfigurationClient` is an `internal` class because it's an implementation detail and not part of the public API of this library. It's purpose is to provide an adapter on top of the `IConsulClient` to provide an interface that better matches what the `ConsulConfigurationProvider` requires. In particular it adds the `IChangeToken Watch(...)` method which makes it possible to write the `ConsulConfigurationProvider` in a similar way to how the other configuration providers are written for sources such as JSON files.

Have you encountered problems trying to use this library with `net471`? I would be happy to help you try and resolve this issue as I would have thought this would be compatible given that this library is compatible down to `net461`.

**Comment by Choc13** [comment]
Given there have been no further questions on this thread I am going to close it. If you still need assistance please feel free to re-open it.
