### ISSUE TITLE
New configuration values not available on reload when additional configuration providers are used

### ISSUE THREAD

**Issue by davidalpert** [wintoncode/Winton.Extensions.Configuration.Consul#97]
I am chasing a problem in my .NET Core 3.1 app using version `3.0.1` of this `Winton.Extensions.Configuration.Consul` library where I can properly register a reload handler to my `IConfiguration` and access the updated configuration values in the handler when I build app configuration like this:
```
      Host.CreateDefaultBuilder()
        .ConfigureAppConfiguration((ctx, config) => {
          config.AddJsonFile("appSettings.json", optional: true);
          config.AddJsonFile("appSettings.Production.json", optional: true);
          config.AddConsul("cabernet", opt =>
          {
            opt.ConsulConfigurationOptions = cco =>
            {
              cco.Address = new Uri("http://localhost:8500");
            };
            opt.ReloadOnChange = true;
            opt.Parser = new SimpleConfigurationParser();
          });
        })

```
and subscribe to change notifications like this:
```
       ChangeToken.OnChange(configuration.GetReloadToken, _ => ConfigChanged(), new object());
```
where `configuration` is the `IConfiguration` instance provided to the `ConfigureServces()` method inside the `IHostingContext.Configuration` property.

When I add the `ConsulConfiguration` to my configuration builder and then add environment and command line args like this, however:
```
      Host.CreateDefaultBuilder()
        .ConfigureAppConfiguration((ctx, config) => {
          config.AddJsonFile("appSettings.json", optional: true);
          config.AddJsonFile("appSettings.Production.json", optional: true);
          config.AddConsul("cabernet", opt =>
          {
            opt.ConsulConfigurationOptions = cco =>
            {
              cco.Address = new Uri("http://localhost:8500");
            };
            opt.ReloadOnChange = true;
            opt.Parser = new SimpleConfigurationParser();
          });
          config.AddEnvironmentVariables();
          config.AddCommandLine(args);
        })
``` 
I still get the change notification but the updated config values are no longer available and access my config values through the `IConfiguration` provider only returns me the old values.

I tried reproducing this in some unit tests (see [code here](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/compare/master...davidalpert:test-multiple-configuration-sources?expand=1)) but am a bit uncertain how the setup for these tests works so my tests are failing when building the ConfigurationRoot. 

In the end I'm not sure whether this problem I'm chasing is in the `Winton.Extensions.Configuration.Consul` library, the `Microsoft.Extensions.Configuration` library, or (most likely) my own use of these two libraries together through misunderstanding a nuance of setup and change token handling.

**Comment by Choc13** [comment]
My best guess here is that this is because when you add those additional config providers they are being added after Consul and so their values take precedence. That is intended behaviour as per the spec for Microsoft.Extensions.Configuration. That would seem to explain why you see the reload event being triggered but the values are not being updated. 

Are setting those values in both Consul and the environment variables and/or the command line ages?

**Comment by davidalpert** [comment]
that's my best guess too, which is why I was hoping to recreate the scenario in a unit test using the `IConfiguration` interface to access values set up in this scenario.

from what I could tell I didn't have the same value set in either place, but I will look again in case I missed something,

**Comment by Choc13** [comment]
Having glanced at the test in the diff you linked to above they look to be OK. What issues were you facing when running them?

**Comment by Choc13** [comment]
Actually, having just tried to run one myself I see an issue. Because it calls:

```
var config = new ConfigurationBuilder()
                .Add(_source)
                .Build();
```

This invokes `_source.Build` which internally create a real `ConsulConfigurationProvider` with a real `ConsulClientFactory` and so tries to make actual network requests. If you want to test multiple configuration providers working together then I think you'd need to write an integration test instead. There are some integration tests under `test/Website/IntegrationTests` which you could extend. Or you could just run that test website on your machine, after adding some more configuration providers, and then debug it.

**Comment by Choc13** [comment]
I have been able to recreate this behaviour using the test website project, but AFAICT it is working as expected. I had the following configuration setup in `Program.cs`:

```
.ConfigureAppConfiguration(
    builder =>
    {
        builder
            .AddConsul(
                "mykey",
                options =>
                {
                    options.ConsulConfigurationOptions =
                        cco => cco.Address = new Uri("https://myconsuladdress");
                    options.Optional = true;
                    options.PollWaitTime = TimeSpan.FromSeconds(5);
                    options.ReloadOnChange = true;
                })
            .AddEnvironmentVariables();
    });
```

I initially had config item `Foo` with a value `"bar"` in Consul and I could access this through the `IConfiguration` interface as expected. I then updated the value and saw that the callback I had registered on the reload token was being fired and the new value was picked up, again as you would expect.

I then repeated the above test, but this time set `Foo` to `"Bar"` in the environment variables (which have the highest precedence in my setup). In this case the value of `Foo` was always `"Bar"` even when the callback on the reload token was called due to a change of value in Consul. 

So from what I can see everything is working as expected and the issue just seems to be that later configuration providers will always take precedence over earlier ones, even in if an earlier provider gets an updated value.

**Comment by davidalpert** [comment]
appreciate the effort, and the pointers with the tests. they behaviour you described matches my understanding and expectations too. will have to keep looking at the configs and env on my end as there must be something I'm missing on my side.
